### ISSUE TITLE
Animations module is broken

### ISSUE THREAD

**Issue by noahdemar** [rland93/rrt_pathplanner#1]
It seems to be depended on some depreciated functions from rrt.py such as make_perlin_world(). A fix would be greatly appreciated!

**Comment by rland93** [comment]
Hi, thanks for the feedback!

Yes, I've been really neglecting the animations module. Going to try to tighten things up and fix in the next couple of days.

If I can ask: How are you planning to use the animations? To see the animations of the RRT being created, or to generate animations of planning in dynamic scenes?

**Comment by noahdemar** [comment]
I was hoping to generate videos similar to your youtube uploads. I want to see the final planned path. 

Also, just a curiosity question. What happens if the perlin slice "rises" to intersect the path finding agent? That is, there is no time to avoid the slice?

Thanks for the quick response. Super cool project!

**Comment by rland93** [comment]
Fixed: 2d2764ecc72976a413032c3c089c0b1a79277366

**Comment by rland93** [comment]
> I was hoping to generate videos similar to your youtube uploads. I want to see the final planned path.
> 
> Also, just a curiosity question. What happens if the perlin slice "rises" to intersect the path finding agent? That is, there is no time to avoid the slice?
> 
> Thanks for the quick response. Super cool project!

Oh, I just realized I didn't actually answer that question.

In that case, the agent just stops in place. I think that's the simplest way to solve that problem. I tried to mitigate that a little bit but it will happen if the world or agent moves too quickly though the world.
